### ISSUE TITLE
Outdoor music programming on Castro

### ISSUE THREAD

**Issue by aprilwebster** [aprilwebster/mountain-view-advocacy#1]

**Comment by bkengland** [comment]
- Open Street Events prioritization: According to https://mountainview.legistar.com/View.ashx?M=F&ID=9079775&GUID=E98F589C-27F8-4E91-A61E-04D95A73FDDD: "On December 10, 2019, Council adopted a Vision Zero Policy and reviewed an initial draft VZAP covering the “7Es”: Engagement, Equity, Engineering, Education, Encouragement, Enforcement, and Evaluation. Strategies included prioritization of projects along the City’s High-Injury Network as part of the Five-Year Capital Improvement Program (CIP), and **Open Streets Events** such as Thursday Night Live.
"Since the adoption of the Vision Zero Policy, staff has collaborated via an interdepartmental Vision Zero Working Group to review capital projects and schedule for inclusion in the City’s Five-Year Capital Improvement Program. Through these discussions, the CIP has been updated to include feasibility, pilot, design, and/or construction projects identified on the City’s High-Injury Network such as El Camino Real Pedestrian and Bikeway Improvements, El Monte Corridor Improvements, California Street Complete Streets Pilot, and Middlefield Road Bikeway Pilot and Study. Staff implemented or planned various Vision Zero Engagement and Encouragement activities, most of which were canceled due to COVID-19. Instead, staff used a portion of SAP-4 funds to implement the Castro StrEATS program, which facilitated outdoor dining and simultaneously achieved the goal of piloting an **Open Streets program**."
- Peter Katz of the Mountain View Chamber of Commerce supports having this in Mountain View.
- To help find performers:
 ** There’s an SF organization behind Flower Piano and similar
 ** West Valley Music downtown (https://www.westvalleymusic.com/)
 ** California Bluegrass Association (https://californiabluegrass.org/)
 ** Community School of Music and Arts (CSMA) (and for general collaboration potential) (http://arts4all.org/)
 ** Local high schools (Mountain View High School (https://mvhs.mvla.net/), Los Altos High School (https://lahs.mvla.net/), Alta Vista High School (https://avhs.mvla.net/), View High School (https://www.viewhighschool.org/), St. Francis High School (http://www.mtnviewacademy.org/), and Foothill (https://foothill.edu/music/) and De Anza (https://www.deanza.edu/music/) Community Colleges to help find performers (and for general collaboration potential)
- Buskers and other artists Bruce likes in particular who would be great to have (or similar artists; some of these are not based around here): Sant Andreu Jazz Band, Alba Armengou, Allie Sherlock, Fabio Rodrigues, Avalon Jazz Band, Tuba Skinny, The Hot Club of San Francisco, Dom La Nena, Stacey Kent, The Tuttles with AJ Lee, Glen Hansard.

**Comment by bkengland** [comment]
To break this down into smaller steps, consider starting with these:
- [ ] Bring up in open public comments at upcoming Council meeting (most or all council members already know about this, so this more to advance in a public setting.
- [ ] Explore options for expanding role of the Performing Arts Committee beyond just the Performing Arts Center (i.e., onto Castro or all streets at least). First step, bring up with the committee during open public comments asking for them to agendize consideration and determination, presumably for approval by City Council.
- [ ] Identify who in the City might develop/own a street performing permit process, and engage with them.
